config/routes.rb
Rails.application.routes.draw do
  get 'customers/alphabetized'

  get 'customers/missing_email'

  resources :customers, only: [:index]

  root to: 'customers#index'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
  belongs_to :province
  validates :full_name, :phone_number, presence: true
  validates :full_name, length: { minimum: 5 }
end

app/models/province.rb
class Province < ApplicationRecord
  has_many :customers
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  def index
    @customers = Customer.all
  end

  def alphabetized
    @customers = Customer.order(:full_name)
  end

  def missing_email
    @customers = Customer.where('email_address == ""')
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/alphabetized.html.erb
<h1>Customers: Alphabetized</h1>

<p><%= link_to 'Index', root_path %> <%= link_to 'Missing Email', customers_missing_email_path %></p>

<p><%= render partial: 'layouts/customer', collection: @customers %></p>

app/views/customers/index.html.erb
<h1>Customers</h1>

<p><%= link_to 'Missing Email', customers_missing_email_path %> <%= link_to 'Alphabetized', customers_alphabetized_path %></p>

<p><%= render partial: 'layouts/customer', collection: @customers %></p>

app/views/customers/missing_email.html.erb
<h1>Customers : Missing Emails</h1>
<p><%= link_to 'Index', root_path %> <%= link_to 'Alphabetized', customers_alphabetized_path %></p>
<p><%= render partial: 'layouts/customer', collection: @customers %></p>

app/views/layouts/_customer.html.erb
<div class="cust">
  <h3><%= customer.full_name %></h3>
  <p class="img"><%= image_tag(customer.image, :alt => customer.full_name) %></p>
  <p>
    <% if customer.province %>
      <strong>Province: </strong><%= customer.province.name %>
    <% else %>
      <strong>Province: </strong> none
    <% end %>
  </p>
  <p>Phone: <%= customer.phone_number %></p>
  <p>Email: <%= customer.email_address %></p>
</div>


app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Challenge6</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>